[package]
name = "clemp"
version = "0.1.0"
authors = ["reslario <reslario.code@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
clipboard-win = "4.4.1"
structopt = "0.3.26"
image = "0.24.2"
rand = "0.8.5"
